# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
workflows:
  build:
    jobs:
      - unit-test-client
      - unit-tests-server
jobs:
  unit-test-client:
    working_directory: ~/src/client
    docker:
      - image: circleci/node:9.2
    steps:
      - checkout
      - run:
          name: Create cache lock file
          command: cat package.json yarn.lock | grep -v version  > cache.lock
      - restore_cache:
          key: node92--{{ arch }}--{{ checksum "cache.lock" }}
      - run:
          name: Install node dependencies
          command: if [ ! -d "node_modules" ]; then yarn; fi
      - save_cache:
          key: node92--{{ arch }}--{{ checksum "cache.lock" }}
          paths:
            - node_modules
      - run:
          name: Lint TS files
          command: yarn lint
      - run:
          name: Unit tests
          command: yarn test
  unit-test-server:
    working_directory: ~/src/server
    docker:
      - image: circleci/node:9.2
    steps:
      - checkout
      - run:
          name: Create cache lock file
          command: cat package.json yarn.lock | grep -v version  > cache.lock
      - restore_cache:
          key: node92--{{ arch }}--{{ checksum "cache.lock" }}
      - run:
          name: Install node dependencies
          command: if [ ! -d "node_modules" ]; then yarn; fi
      - save_cache:
          key: node92--{{ arch }}--{{ checksum "cache.lock" }}
          paths:
            - node_modules
      - run:
          name: Lint TS files
          command: yarn lint
      - run:
          name: Unit tests
          command: yarn test